### ISSUE TITLE
Support for C# language

### ISSUE THREAD

**Issue by majidmadadi** [konradkeska/subliminal-next#1]
Function names and function calls are both in red color in .cs files. Does this addon support c# language? Do you have any plan to add support for c# language?

**Comment by konradkeska** [comment]
I am not too experienced with C#, but as far as I am concerned and from what I have just checked - there is only one scope for C# function call and declaration in VS Code. I think there is nothing I can do in this case.

By the way, you can use `CMD + SHIFT + P` > `'inspect TM scopes'` to check scopes yourself, I find it kind of useful.

**Comment by majidmadadi** [comment]
Dear Konrad,
Thank you for your answer,
This extension solved the problem:
https://marketplace.visualstudio.com/items?itemName=maximetinu.identical-sublime-monokai-csharp-theme-colorizer

Sent from Mail for Windows 10
