### ISSUE TITLE
a quick question 

### ISSUE THREAD

**Issue by enzime4u** [konradkeska/subliminal-next#3]
Can you please let me know how to change the return keyword from italic to normal  ? Kept trying to tweak you theme but I just couldn't find it or maybe I am over-doing something.
Thank you

**Comment by konradkeska** [comment]
It is normal by default, unless you've changed it.

If you wish to edit it, you can set `keyword.control.flow` color token in theme .json file to whatever you like (in your case it will be `"fontStyle"`) :)

Hope it helps!
KK

**Comment by enzime4u** [comment]
I see.. thank you very much !!!
